# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e70be6bb9b11dbc39d37bb783b4935340ecea8dbd1bd9d8b710cead7076dc59ff737ad29b037e52f6d07b4e85b3ce06e3ee7ae3faf1ba1ca06dae17155cfddd5

test:
  secret_key_base: c06525fe9effb927a490b0298e16a578edd0eabfcbabf7d2bfb452b07e1d2bca181bc1e457ea24dfe26e85e112852ea74a5abb7331c40b2fa2e021b6e37dacc9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
